version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
    - 5672:5672
    - 15672:15672
    
  configuration-service:
    image: searva/spring-cloud-config-server:0.0.1-SNAPSHOT
    volumes:
    - /home/sergio/git-localconfig-repo:/git-localconfig-repo
    ports:
    - 8888:8888
    links:
    - rabbitmq
    depends_on:
    - rabbitmq
    environment:
    - SPRING_RABBITMQ_HOST=rabbitmq
    
  oauth-server:
    image: searva/oauth-authorization-server:0.0.1-SNAPSHOT
    ports:
    - 9999:9999
    
  limits-service:
    image: searva/limits-service:0.0.1-SNAPSHOT
    links:
    - rabbitmq
    - configuration-service
    depends_on:
    - rabbitmq
    - oauth-server
    - configuration-service
    environment:
    - SPRING_RABBITMQ_HOST=rabbitmq
    - CONFIGURATION_HOST=configuration-service
    
  app-ui:
    image: searva/spring-security-sso-ui:0.0.1-SNAPSHOT
    ports:
    - 8089:8089
    links:
    - oauth-server
    - limits-service
    depends_on:
    - oauth-server
    - limits-service
    environment:
    - OAUTH2_SERVER_HOST=oauth-server
    - LIMITS_SERVICE_HOST=limits-service