server:
    port: 8089
    servlet:
      context-path: /ui
    
security:
  oauth2:
    client:
      clientId: fooClientIdPassword
      clientSecret: secret
      accessTokenUri: http://${OAUTH2_SERVER_HOST:localhost}:9999/oauth/token
      userAuthorizationUri: http://localhost:9999/oauth/authorize
    resource:
      userInfoUri: http://localhost:9999/user
      preferTokenInfo: false

spring:
  thymeleaf:
    cache: false 
    
limits-service.endpoint: http://${LIMITS_SERVICE_HOST:localhost}:8080/limits  
